import { Department } from './types';

export const INITIAL_DATA: Department[] = [
  {
    id: '1',
    srNo: '1.',
    name: 'Agriculture, Supply & Prices Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '1-1', name: '1. Directorate General, Agriculture Extension, Sindh', focalPerson: 'Secretary' },
      { id: '1-2', name: '2. Directorate General, Agriculture, Research, Sindh', focalPerson: 'Secretary' },
      { id: '1-3', name: '3. Directorate General Agriculture Engineering & Water Management, Sindh', focalPerson: 'Secretary' },
      { id: '1-4', name: '4. Directorate General, Bureau of Supply & Prices, Sindh', focalPerson: 'Secretary' },
      { id: '1-5', name: '5. Directorate of Agriculture Statistics, Sindh.', focalPerson: 'Secretary' },
      { id: '1-6', name: '6. Directorate of Plant Protection', focalPerson: 'Secretary' },
      { id: '1-7', name: '7. Sindh Seed Corporation', focalPerson: 'Secretary' },
      { id: '1-8', name: '8. Sindh Agricultural Supplies Organization (SASO)', focalPerson: 'Secretary' },
      { id: '1-9', name: '9. Sindh Horticulture Development Board', focalPerson: 'Secretary' },
      { id: '1-10', name: '10. Agriculture Training Institute (ATI), Sakrand', focalPerson: 'Secretary' },
      { id: '1-11', name: '11. Sindh Agriculture Research Institute, Tando Jam.', focalPerson: 'Secretary' },
      { id: '1-12', name: '12. Wheat Research Institute, Sakrand', focalPerson: 'Secretary' },
      { id: '1-13', name: '13. Oilseed Research Institute', focalPerson: 'Secretary' },
      { id: '1-14', name: '14. Horticulture Research Institute, Mirpurkhas', focalPerson: 'Secretary' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '2',
    srNo: '2.',
    name: 'Auqaf Religious Affairs Zakat & Ushr Department, Government of Sindh.',
    focalPerson: 'Secretary',
    offices: [
      { id: '2-1', name: '1. Office of the Chief Administrator Auqaf, Sindh', focalPerson: 'Secretary' },
      { id: '2-2', name: '2. Directorate of Zakat & Ushr, Sindh', focalPerson: 'Secretary' },
      { id: '2-3', name: '3. Research & Training Institute (Auqaf), Karachi', focalPerson: 'Secretary' },
      { id: '2-4', name: '4. Sindh Quran Board', focalPerson: 'Secretary' },
      { id: '2-5', name: '5. Provincial Zakat Council, Sindh', focalPerson: 'Secretary' },
      { id: '2-6', name: '6. Office of Administrator Auqaf, Karachi', focalPerson: 'Secretary' },
      { id: '2-7', name: '7. Office of Administrator Auqaf, Hyderabad', focalPerson: 'Secretary' },
      { id: '2-8', name: '8. Office of Administrator Auqaf, Sukkur', focalPerson: 'Secretary' },
      { id: '2-9', name: '9. Office of Administrator Auqaf, Larkana', focalPerson: 'Secretary' },
      { id: '2-10', name: '10. Office of Administrator Auqaf, Mirpurkhas', focalPerson: 'Secretary' },
      { id: '2-11', name: '11. Office of Administrator Auqaf, Shaheed Benazirabad', focalPerson: 'Secretary' },
      { id: '2-12', name: '12. Shrine Management (Lal Shahbaz Qalandar, Sehwan)', focalPerson: 'Secretary' },
      { id: '2-13', name: '13. Shrine Management (Shah Abdul Latif Bhittai, Bhitshah)', focalPerson: 'Secretary' },
      { id: '2-14', name: '14. Shrine Management (Abdullah Shah Ghazi, Karachi)', focalPerson: 'Secretary' },
      { id: '2-15', name: '15. Shrine Management (Sachal Sarmast, Ranipur)', focalPerson: 'Secretary' },
      { id: '2-16', name: '16. Shrine Management (Syed Misri Shah, Karachi)', focalPerson: 'Secretary' },
      { id: '2-17', name: '17. Ittihad-e-Bainul Muslimeen Committee (Interfaith Harmony)', focalPerson: 'Secretary' },
      { id: '2-18', name: '18. Seerat-un-Nabi Council, Sindh', focalPerson: 'Secretary' },
      { id: '2-19', name: '19. District Zakat & Ushr Committees (All Districts)', focalPerson: 'Secretary' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '3',
    srNo: '3.',
    name: 'Board of Revenue Sindh',
    focalPerson: 'Senior Member / Secretary',
    offices: [
      { id: '3-1', name: '1. Directorate of Settlement, Survey and Land Records, Sindh' },
      { id: '3-2', name: '2. Inspectorate of Registration, Sindh' },
      { id: '3-3', name: '3. Relief and Rehabilitation Wing, Sindh' },
      { id: '3-4', name: '4. Project Management Unit (PMU) - LARMIS (Computerization of Land Records)' },
      { id: '3-5', name: '5. Sindh Board of Revenue Training Institute, Hyderabad' },
      { id: '3-6', name: '6. Land Utilization Wing, Sindh' },
      { id: '3-7', name: '7. Stamps & Registration Wing' },
      { id: '3-8', name: '8. Consolidation of Holdings, Sindh' },
      { id: '3-9', name: '9. Sindh Land Commission (Secretariat)' },
      { id: '3-10', name: '10. Goth Abad Project Cell' },
      { id: '3-11', name: '11. Office of the Full Board of Revenue, Sindh' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '4',
    srNo: '4.',
    name: 'Bureau of Statistics Planning & Development Department, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '4-1', name: '1. Sindh Bureau of Statistics (Headquarter), Karachi' },
      { id: '4-2', name: '2. Regional Office, Bureau of Statistics, Hyderabad' },
      { id: '4-3', name: '3. Regional Office, Bureau of Statistics, Sukkur' },
      { id: '4-4', name: '4. Regional Office, Bureau of Statistics, Larkana' },
      { id: '4-5', name: '5. Regional Office, Bureau of Statistics, Mirpurkhas' },
      { id: '4-6', name: '6. Regional Office, Bureau of Statistics, Shaheed Benazirabad' },
      { id: '4-7', name: '7. Regional Office, Bureau of Statistics, Banbhore (Thatta)' },
      { id: '4-8', name: '8. GIS & Mapping Cell, Bureau of Statistics' },
      { id: '4-9', name: '9. Data Processing & IT Centre' },
      { id: '4-10', name: '10. Price Statistics & Publication Section' },
      { id: '4-11', name: '11. Household & Industrial Statistics Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '5',
    srNo: '5.',
    name: 'Benazir Bhutto Shaheed Human Resource, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '5-1', name: '1. Benazir Bhutto Shaheed Human Resource Research & Development Board (Headquarter), Karachi' },
      { id: '5-2', name: '2. Benazir Bhutto Shaheed Youth Development Program (BBSYDP) Management Unit' },
      { id: '5-3', name: '3. Regional Directorate, BBSHRRDB, Karachi' },
      { id: '5-4', name: '4. Regional Directorate, BBSHRRDB, Hyderabad' },
      { id: '5-5', name: '5. Regional Directorate, BBSHRRDB, Sukkur' },
      { id: '5-6', name: '6. Regional Directorate, BBSHRRDB, Larkana' },
      { id: '5-7', name: '7. Regional Directorate, BBSHRRDB, Mirpurkhas' },
      { id: '5-8', name: '8. Regional Directorate, BBSHRRDB, Shaheed Benazirabad' },
      { id: '5-9', name: '9. Planning, Monitoring & Evaluation Cell' },
      { id: '5-10', name: '10. Technical & Vocational Education Training (TVET) Unit' },
      { id: '5-11', name: '11. Placement & Career Counseling Cell' },
      { id: '5-12', name: '12. Skill Development Coordination Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '6',
    srNo: '6.',
    name: 'College Education Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '6-1', name: '1. Directorate General Colleges, Sindh' },
      { id: '6-2', name: '2. Regional Directorate Colleges, Karachi' },
      { id: '6-3', name: '3. Regional Directorate Colleges, Hyderabad' },
      { id: '6-4', name: '4. Regional Directorate Colleges, Sukkur' },
      { id: '6-5', name: '5. Regional Directorate Colleges, Larkana' },
      { id: '6-6', name: '6. Regional Directorate Colleges, Mirpurkhas' },
      { id: '6-7', name: '7. Regional Directorate Colleges, Shaheed Benazirabad' },
      { id: '6-8', name: '8. Sindh Educational Endowment Fund Trust' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '7',
    srNo: '7.',
    name: 'Chief Minister Sindh, C.M. House',
    focalPerson: 'Principal Secretary',
    offices: [
      { id: '7-1', name: '1. Chief Minister Secretariat' },
      { id: '7-2', name: '2. Chief Minister Inspection, Enquiries & Implementation Team' },
      { id: '7-3', name: '3. Strategic Reform Unit (SRU), CM House' },
      { id: '7-4', name: '4. Public Complaint Cell' },
      { id: '7-5', name: '5. Protocol Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '8',
    srNo: '8.',
    name: 'Chief Minister’s Inspection Enquiries & Implementation Team.',
    focalPerson: 'Chairman',
    offices: [
      { id: '8-1', name: '1. Monitoring & Evaluation Cell' },
      { id: '8-2', name: '2. Enquiries & Implementation Wing' },
      { id: '8-3', name: '3. Special Inspection Squads' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '9',
    srNo: '9.',
    name: 'Cooperation Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '9-1', name: '1. Registrar Cooperative Societies, Sindh' },
      { id: '9-2', name: '2. Sindh Cooperative Bank (Affiliated)' },
      { id: '9-3', name: '3. Cooperative Training Institute, Hyderabad' },
      { id: '9-4', name: '4. Regional Directorates of Cooperative Societies' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '10',
    srNo: '10.',
    name: 'Culture Tourism & Archive Department',
    focalPerson: 'Secretary',
    offices: [
      { id: '10-1', name: '1. Directorate of Culture, Sindh' },
      { id: '10-2', name: '2. Directorate of Antiquities and Archaeology, Sindh' },
      { id: '10-3', name: '3. Directorate of Archives, Sindh' },
      { id: '10-4', name: '4. Directorate of Tourism, Sindh' },
      { id: '10-5', name: '5. Sindh Cultural Heritage & Advisory Committee' },
      { id: '10-6', name: '6. Gorakh Hill Development Authority (GHDA)' },
      { id: '10-7', name: '7. Sindh Language Authority (SLA), Hyderabad' },
      { id: '10-8', name: '8. Sindhi Adabi Board, Jamshoro' },
      { id: '10-9', name: '9. Shah Abdul Latif Bhitai Chair' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '11',
    srNo: '11.',
    name: 'Department of Empowerment of Persons with Disabilities, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '11-1', name: '1. Directorate of Special Education, Sindh' },
      { id: '11-2', name: '2. Rehabilitation Centers for Disabled (Provincial Network)' },
      { id: '11-3', name: '3. Vocational Training Centers for Differently Abled Persons' },
      { id: '11-4', name: '4. Sindh Occupational Therapy Centre' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '12',
    srNo: '12.',
    name: 'Education & Literacy Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '12-275', name: '1. Director General, Directorate of Inspection & Registration of Private Institutes' },
      { id: '12-276', name: '2. Director Education (Primary), Karachi Region' },
      { id: '12-277', name: '3. District Education Officer (Primary), District South, Karachi' },
      { id: '12-278', name: '4. District Education Officer (Primary), District Keamari, Karachi' },
      { id: '12-279', name: '5. District Education Officer (Primary), District Malir, Karachi' },
      { id: '12-280', name: '6. District Education Officer (Primary), District Central, Karachi' },
      { id: '12-281', name: '7. District Education Officer (Primary), District West, Karachi' },
      { id: '12-282', name: '8. Director Education (Secondary), Karachi Region' },
      { id: '12-283', name: '9. District Education Officer (Secondary), District South, Karachi' },
      { id: '12-284', name: '10. District Education Officer (Secondary), District Keamari, Karachi' },
      { id: '12-285', name: '11. District Education Officer (Secondary), District Malir, Karachi' },
      { id: '12-286', name: '12. District Education Officer (Secondary), District Central, Karachi' },
      { id: '12-287', name: '13. District Education Officer (Secondary), District West, Karachi' },
      { id: '12-288', name: '14. Director Education (Primary), Hyderabad Region' },
      { id: '12-289', name: '15. District Education Officer (Primary), District Jamshoro' },
      { id: '12-290', name: '16. District Education Officer (Primary), District Dadu' },
      { id: '12-291', name: '17. District Education Officer (Primary), District Tando Muhammad Khan' },
      { id: '12-292', name: '18. District Education Officer (Primary), District Thatta' },
      { id: '12-293', name: '19. District Education Officer (Primary), District Sujawal' },
      { id: '12-294', name: '20. District Education Officer (Primary), District Matiari' },
      { id: '12-295', name: '21. District Education Officer (Primary), District Badin' },
      { id: '12-296', name: '22. District Education Officer (Primary), District Tando Allahyar' },
      { id: '12-297', name: '23. District Education Officer (Primary), District Sukkur' },
      { id: '12-298', name: '24. District Education Officer (Primary), District Hyderabad' },
      { id: '12-299', name: '25. District Education Officer (Primary), District Mirpurkhas' },
      { id: '12-300', name: '26. District Education Officer (Primary), District Umerkot' },
      { id: '12-301', name: '27. District Education Officer (Primary), District Shaheed Benazirabad' },
      { id: '12-302', name: '28. District Education Officer (Primary), District Sanghar' },
      { id: '12-303', name: '29. Director Education (Secondary), Hyderabad Region' },
      { id: '12-304', name: '30. District Education Officer (Secondary), District Jamshoro' },
      { id: '12-305', name: '31. District Education Officer (Secondary), District Dadu' },
      { id: '12-306', name: '32. District Education Officer (Secondary), District Tando M. Khan' },
      { id: '12-307', name: '33. District Education Officer (Secondary), District Thatta' },
      { id: '12-308', name: '34. District Education Officer (Secondary), District Sujawal' },
      { id: '12-309', name: '35. District Education Officer (Secondary), District Matiari' },
      { id: '12-310', name: '36. District Education Officer (Secondary), District Badin' },
      { id: '12-311', name: '37. District Education Officer (Secondary), District Tando Allahyar' },
      { id: '12-312', name: '38. Director Education (Secondary), Sukkur Region' },
      { id: '12-313', name: '39. District Education Officer (Secondary), District Khairpur' },
      { id: '12-314', name: '40. District Education Officer (Secondary), District Larkana' },
      { id: '12-315', name: '41. District Education Officer (Secondary), District Ghotki' },
      { id: '12-316', name: '42. District Education Officer (Secondary), District Sukkur' },
      { id: '12-317', name: '43. Director Education (Secondary), Larkana Region' },
      { id: '12-318', name: '44. District Education Officer (Secondary), District Qambar @ Shahdadkot' },
      { id: '12-319', name: '45. District Education Officer (Secondary), District Shikarpur' },
      { id: '12-320', name: '46. District Education Officer (Secondary), District Jacobabad' },
      { id: '12-321', name: '47. Director Education (Primary), Larkana Region' },
      { id: '12-322', name: '48. District Education Officer (Primary), District Qambar @ Shahdadkot' },
      { id: '12-323', name: '49. District Education Officer (Primary), District Kashmore @ Kandhkot' },
      { id: '12-324', name: '50. District Education Officer (Primary), District Larkana' },
      { id: '12-325', name: '51. District Education Officer (Primary), District Shikarpur' },
      { id: '12-326', name: '52. District Education Officer (Primary), District Jacobabad' },
      { id: '12-327', name: '53. Director Education (Primary), Shaheed Benazirabad Region' },
      { id: '12-328', name: '54. District Education Officer (Primary), District Naushahro Feroze' },
      { id: '12-329', name: '55. Director Education (Secondary), Shaheed Benazirabad Region' },
      { id: '12-330', name: '56. District Education Officer (Secondary), District Sanghar' },
      { id: '12-331', name: '57. District Education Officer (Secondary), District Naushahro Feroze' },
      { id: '12-332', name: '58. Director Education (Secondary), Mirpurkhas Region' },
      { id: '12-333', name: '59. District Education Officer (Secondary), District Tharparkar' },
      { id: '12-334', name: '60. District Education Officer (Secondary), District Umerkot' },
      { id: '12-335', name: '61. Director Education (Primary), Mirpurkhas Region' },
      { id: '12-336', name: '62. District Education Officer (Primary), District Tharparkar' },
      { id: '12-1', name: '63. Reform and Support Unit (RSU)' },
      { id: '12-2', name: '64. Sindh Education Foundation (SEF)' },
      { id: '12-3', name: '65. Sindh Text Book Board (STBB), Jamshoro' },
      { id: '12-4', name: '66. Provincial Institute of Teacher Education (PITE), Shaheed Benazirabad' },
      { id: '12-5', name: '67. Sindh Teacher Education Development Authority (STEDA)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '13',
    srNo: '13.',
    name: 'Environment Climate Change & Coastal Development Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '13-1', name: '1. Sindh Environmental Protection Agency (SEPA)' },
      { id: '13-2', name: '2. Sindh Coastal Development Authority (SCDA)' },
      { id: '13-3', name: '3. Sindh Environmental Protection Tribunal' },
      { id: '13-4', name: '4. Climate Change Cell, Sindh' },
      { id: '13-5', name: '5. Environmental Research & Development Wing' },
      { id: '13-6', name: '6. Coastal Development Project Implementation Units' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '14',
    srNo: '14.',
    name: 'Energy Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '14-1', name: '1. Sindh Coal Authority (SCA)' },
      { id: '14-2', name: '2. Sindh Transmission & Dispatch Company (STDC)' },
      { id: '14-3', name: '3. Sindh Lakhra Coal Mining Company (SLCMC)' },
      { id: '14-4', name: '4. Directorate of Alternative Energy, Sindh' },
      { id: '14-5', name: '5. Directorate of Oil & Gas, Sindh' },
      { id: '14-6', name: '6. Sindh Solar Energy Project (SSEP)' },
      { id: '14-7', name: '7. Thar Coal Energy Board (Secretariat)' },
      { id: '14-8', name: '8. Renewable Energy & Energy Efficiency Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '15',
    srNo: '15.',
    name: 'Enquiries & Anticorruption Establishment, Government of Sindh.',
    focalPerson: 'Chairman',
    offices: [
      { id: '15-1', name: '1. Directorate of Enquiries' },
      { id: '15-2', name: '2. Anti-Corruption Regional Offices (Karachi, Hyderabad, Sukkur, Larkana, Mirpurkhas, SBA)' },
      { id: '15-3', name: '3. Legal and Prosecution Wing, ACE' },
      { id: '15-4', name: '4. Technical Wing (Civil, Electric & Mechanical)' },
      { id: '15-5', name: '5. IT & Digital Forensics Unit, ACE' },
      { id: '15-6', name: '6. Special Anti-Corruption Courts (Liaison)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '16',
    srNo: '16.',
    name: 'Excise Taxation & Narcotics Control Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '16-1', name: '1. Director General , Narcotics Control Excise & Taxation Karachi' },
      { id: '16-2', name: '2. Director General, Excise & Taxation, Karachi' },
      { id: '16-3', name: '3. Director (MVR), Excise & Taxation Karachi' },
      { id: '16-4', name: '4. Director (Excise), Excise & Taxation Karachi' },
      { id: '16-5', name: '5. Director (Taxes-II), Excise & TAxation Karachi' },
      { id: '16-6', name: '6. Excise & Taxation Officer, District South Karachi' },
      { id: '16-7', name: '7. Excise & Taxation Officer, District East Karachi' },
      { id: '16-8', name: '8. Excise & Taxation Officer, District West Karachi' },
      { id: '16-9', name: '9. Excise & Taxation Officer, District Central Karachi' },
      { id: '16-10', name: '10. Excise & Taxation Officer, District Malir Karachi' },
      { id: '16-11', name: '11. Excise & Taxation Officer, District Korangi Karachi' },
      { id: '16-12', name: '12. Excise & Taxation Officer, District Keamari Karachi' },
      { id: '16-13', name: '13. Director Excise & Taxation SBA Division, Shaheed Benazirabad' },
      { id: '16-14', name: '14. Excise & Taxation Officer, District Shaheed Benazirabad' },
      { id: '16-15', name: '15. Excise & Taxation Officer, District Sanghar' },
      { id: '16-16', name: '16. Excise & Taxation Officer, District Naushehro Feroze.' },
      { id: '16-17', name: '17. Director Excise & Taxation Mirpurkhas Division, Mirpurkhas' },
      { id: '16-18', name: '18. Excise & Taxation Officer, District Mirpurkhas.' },
      { id: '16-19', name: '19. Excise & Taxation Officer, District Tharparkar.' },
      { id: '16-20', name: '20. Excise & Taxation Officer, District Umerkot.' },
      { id: '16-21', name: '21. Director Excise & Taxation Hyderabad Division, Hyderabad' },
      { id: '16-22', name: '22. Excise & Taxation Officer, District Hyderabad.' },
      { id: '16-23', name: '23. Excise & Taxation Officer, District Tando Allahyar' },
      { id: '16-24', name: '24. Excise & Taxation Officer, District Dadu' },
      { id: '16-25', name: '25. Excise & Taxation Officer, District Tando Muhammad Khan.' },
      { id: '16-26', name: '26. Excise & Taxation Officer, District Matiari.' },
      { id: '16-27', name: '27. Excise & Taxation Officer, District Jamshoro.' },
      { id: '16-28', name: '28. Excise & Taxation Officer, District Thatta.' },
      { id: '16-29', name: '29. Excise & Taxation Officer, District Sujawal.' },
      { id: '16-30', name: '30. Excise & Taxation Officer, District Badin.' },
      { id: '16-31', name: '31. Director Excise & Taxation Sukkur Division, Sukkur' },
      { id: '16-32', name: '32. Excise & Taxation Officer, District Sukkur.' },
      { id: '16-33', name: '33. Excise & Taxation Officer, District Khairpur.' },
      { id: '16-34', name: '34. Excise & Taxation Officer, District Ghotki.' },
      { id: '16-35', name: '35. Director Excise & Taxation Larkana Division, Larkana' },
      { id: '16-36', name: '36. Excise & Taxation Officer, District Larkana.' },
      { id: '16-37', name: '37. Excise & Taxation Officer, District Shikarpur.' },
      { id: '16-38', name: '38. Excise & Taxation Officer, District Jacobabad.' },
      { id: '16-39', name: '39. Excise & Taxation Officer, District Kashmore Kandhkot.' },
      { id: '16-40', name: '40. Excise & Taxation Officer, District Qambar Shahdadkot.' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '17',
    srNo: '17.',
    name: 'Finance Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '17-1', name: '1. Office of the Accountant General (AG), Sindh' },
      { id: '17-2', name: '2. Directorate of Treasuries and Accounts, Sindh' },
      { id: '17-3', name: '3. Sindh Revenue Board (SRB)' },
      { id: '17-4', name: '4. Local Fund Audit, Sindh' },
      { id: '17-5', name: '5. Sindh Pension Fund Management Unit' },
      { id: '17-6', name: '6. Public Private Partnership (PPP) Unit' },
      { id: '17-7', name: '7. Resource Mobilization Unit (RMU)' },
      { id: '17-8', name: '8. Debt Management Unit' },
      { id: '17-9', name: '9. Economic Reform Unit (ERU)' },
      { id: '17-10', name: '10. Sindh Social Protection Authority (SSPA)' },
      { id: '17-11', name: '11. District Accounts Offices (All Districts)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '18',
    srNo: '18.',
    name: 'Health Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '18-215', name: '1. Medical Superintendent Dr. Ruth K.M Pfau, Civil Hospital Karachi' },
      { id: '18-216', name: '2. Medical Superintendent, SMMBBIT, Shaheed Mohtarma Benazir Bhutto Institute of Trauma, Karachi' },
      { id: '18-217', name: '3. Executive Director, Jinnah Postgraduate Medical Centre, Karachi' },
      { id: '18-218', name: '4. Executive Director, National Institute of Child Health Karachi' },
      { id: '18-219', name: '5. Medical Superintendent, Sindh Government Lyari General Hospital, Rangiwara Karachi' },
      { id: '18-220', name: '6. Medical Superintendent, Sindh Government Hospital, Saudabad, Karachi' },
      { id: '18-221', name: '7. Medical Superintendent, Sindh Government Hospital Ibrahim Hydri, Karachi' },
      { id: '18-222', name: '8. Medical Superintendent, Sindh Government Hospital New Karachi North Karachi, Karachi' },
      { id: '18-223', name: '9. Medical Superintendent, Sindh Government Children Hospital, North Nazimabad, Karachi' },
      { id: '18-224', name: '10. Medical Superintendent, Sindh Government 50 Bedded Hospital Gadap City, Karachi' },
      { id: '18-225', name: '11. Medical Superintendent, Sindh Government Urban Health Center, North Karachi, Karachi' },
      { id: '18-226', name: '12. Medical Superintendent, Sindh Government Hospital Liaquatabad, Gulberg Town, Karachi' },
      { id: '18-227', name: '13. Medical Superintendent, Sindh Government Hospital Korangi, Landhi Town, Karachi' },
      { id: '18-228', name: '14. Director Health Sukkur Division, Sukkur' },
      { id: '18-229', name: '15. District Health Officer, District Sukkur' },
      { id: '18-230', name: '16. District Health Officer, District Khairpur' },
      { id: '18-231', name: '17. District Health Officer, District Ghotki' },
      { id: '18-232', name: '18. Director Health Shaheed Benazirabad Division, Shaheed Benazirabad' },
      { id: '18-233', name: '19. District Health Officer, District Shaheed Benazirabad' },
      { id: '18-234', name: '20. District Health Officer, District Sanghar' },
      { id: '18-235', name: '21. District Health Officer, District Naushero Feroze' },
      { id: '18-236', name: '22. Director Health Hyderabad Division, Hyderabad' },
      { id: '18-237', name: '23. District Health Officer, District Hyderabad' },
      { id: '18-238', name: '24. District Health Officer, District Tando Allahyar' },
      { id: '18-239', name: '25. District Health Officer, District Dadu' },
      { id: '18-240', name: '26. District Health Officer, District Tando Muhammad Khan' },
      { id: '18-241', name: '27. District Health Officer, District Matiari' },
      { id: '18-242', name: '28. District Health Officer, District Jamshoro' },
      { id: '18-243', name: '29. District Health Officer, District Thatta' },
      { id: '18-244', name: '30. District Health Officer, District Sujawal' },
      { id: '18-245', name: '31. District Health Officer, District Badin' },
      { id: '18-246', name: '32. Director Health Larkana Division, Larkana' },
      { id: '18-247', name: '33. District Health Officer, District Larkana' },
      { id: '18-248', name: '34. District Health Officer, District Shikarpur' },
      { id: '18-249', name: '35. District Health Officer, District Jacobabad' },
      { id: '18-250', name: '36. District Health Officer, District Kashmore Kandhkot' },
      { id: '18-251', name: '37. District Health Officer, District Qambar Shahdadkot' },
      { id: '18-252', name: '38. Director Health Karachi Division, Karachi' },
      { id: '18-253', name: '39. District Health Officer, District District South Karachi' },
      { id: '18-254', name: '40. District Health Officer, District District East Karachi' },
      { id: '18-255', name: '41. District Health Officer, District District West Karachi' },
      { id: '18-256', name: '42. District Health Officer, District District Central Karachi' },
      { id: '18-257', name: '43. District Health Officer, District District Malir Karachi' },
      { id: '18-258', name: '44. District Health Officer, District District Korangi Karachi' },
      { id: '18-259', name: '45. District Health Officer, District District Keamari Karachi' },
      { id: '18-260', name: '46. Director Health Mirpurkhas Division, Mirpurkhas' },
      { id: '18-261', name: '47. District Health Officer, District Mirpurkhas' },
      { id: '18-262', name: '48. District Health Officer, District Tharparkar' },
      { id: '18-263', name: '49. District Health Officer, District Umerkot' },
      { id: '18-1', name: '50. Directorate General Health Services, Sindh (Hyderabad)' },
      { id: '18-4', name: '51. National Institute of Cardiovascular Diseases (NICVD)' },
      { id: '18-6', name: '52. Sindh Institute of Urology and Transplantation (SIUT)' },
      { id: '18-8', name: '53. Sindh Health Care Commission (SHCC)' },
      { id: '18-9', name: '54. Sindh Blood Transfusion Authority' },
      { id: '18-12', name: '55. Vertical Programs (EPI, Lady Health Workers, TB/AIDS Control)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '19',
    srNo: '19.',
    name: 'Home Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '19-96', name: '1. Inspector General of Police Sindh (IGP)' },
      { id: '19-97', name: '2. SSP District South Karachi' },
      { id: '19-98', name: '3. SSP District Keamari Karachi' },
      { id: '19-99', name: '4. SSP District City Karachi' },
      { id: '19-100', name: '5. SP Headquarter South, Garden Karachi' },
      { id: '19-101', name: '6. SP Complaint Cell District South Karachi' },
      { id: '19-102', name: '7. SP Complaint Cell District Keamari Karachi' },
      { id: '19-103', name: '8. SP Complaint Cell, City Karachi' },
      { id: '19-104', name: '9. SP Investigation South-I, Karachi' },
      { id: '19-105', name: '10. SP Investigation South-II, Karachi' },
      { id: '19-106', name: '11. SP Investigation South-III, Karachi' },
      { id: '19-107', name: '12. SSP District East Karachi' },
      { id: '19-108', name: '13. SSP Complaint Cell District Korangi, Karachi' },
      { id: '19-109', name: '14. SSP District Korangi, Karachi' },
      { id: '19-110', name: '15. SSP Complaint Cell District East Karachi' },
      { id: '19-111', name: '16. SSP Complaint Cell District Malir Karachi' },
      { id: '19-112', name: '17. SP Headquarters East Zone Karachi' },
      { id: '19-113', name: '18. SP Investigation East-I East Karachi' },
      { id: '19-114', name: '19. SP Investigation East-II Malir Karachi' },
      { id: '19-115', name: '20. SP Investigation East-II Korangi Karachi' },
      { id: '19-116', name: '21. SP Landhi Division East Zone, Karachi' },
      { id: '19-117', name: '22. SP Complaint Cell District Malir, Karachi' },
      { id: '19-118', name: '23. SP Gulshan Division East Zone, Karachi' },
      { id: '19-119', name: '24. SP Jamshed Division, East Zone, Karachi' },
      { id: '19-120', name: '25. SSP District West, Karachi' },
      { id: '19-121', name: '26. SSP District Central, Karachi' },
      { id: '19-122', name: '27. SP Headquarter West Karachi' },
      { id: '19-123', name: '28. SP Orangi Division District West Karachi' },
      { id: '19-124', name: '29. SP Complaint Cell, District Keamari, Karachi' },
      { id: '19-125', name: '30. SP Complaint Cell, District Central, Karachi' },
      { id: '19-126', name: '31. SP Gulberg Division, West Zone Karachi' },
      { id: '19-127', name: '32. SP Investigation South-I District West Karachi' },
      { id: '19-128', name: '33. SP Investigation South-II, District Central Karachi' },
      { id: '19-129', name: '34. DIGP Traffic Karachi Range' },
      { id: '19-130', name: '35. ADIGP (Admin), Traffic Karachi' },
      { id: '19-131', name: '36. SP Traffic, South Karachi' },
      { id: '19-132', name: '37. SP Traffic, East Karachi' },
      { id: '19-133', name: '38. SP Traffic, West Karachi' },
      { id: '19-134', name: '39. SP Traffic, Central Karachi' },
      { id: '19-135', name: '40. SP Traffic, Malir Karachi' },
      { id: '19-136', name: '41. SP Traffic, Korangi Karachi' },
      { id: '19-137', name: '42. SP Traffic, City Karachi' },
      { id: '19-138', name: '43. SSP Anti Vehicle Lifting Cell (AVLC) Karachi' },
      { id: '19-139', name: '44. SSP Specialized Investigation Unit (SIU), Karachi' },
      { id: '19-140', name: '45. SSP Anti Violent Crime Cell, Karachi' },
      { id: '19-141', name: '46. SP Madadgar-15/Mahafiz Force, Karachi' },
      { id: '19-142', name: '47. SP Foreigners Security Cell, Karachi' },
      { id: '19-143', name: '48. SSP Commandant SSU, Karachi' },
      { id: '19-144', name: '49. SP Special Security Unit, Karachi' },
      { id: '19-145', name: '50. SP Special Security Unit (Operation), Karachi' },
      { id: '19-146', name: '51. SP Crowd Management Unit, Range' },
      { id: '19-147', name: '52. SP Court Police, Karachi' },
      { id: '19-148', name: '53. SP Crime Scene Unit (CSU), Karachi' },
      { id: '19-150', name: '54. SP Security-I, Karachi' },
      { id: '19-151', name: '55. SP Security-II, Karachi' },
      { id: '19-152', name: '56. DIGP Hyderabad Range' },
      { id: '19-153', name: '57. SSP District Hyderabad' },
      { id: '19-154', name: '58. SP District Tando Allahyar' },
      { id: '19-155', name: '59. SSP District Dadu' },
      { id: '19-156', name: '60. SP District Tando Muhammad Khan' },
      { id: '19-157', name: '61. SP District Matiari' },
      { id: '19-158', name: '62. SP District Jamshoro' },
      { id: '19-159', name: '63. SP District Thatta' },
      { id: '19-160', name: '64. SP District Sujawal' },
      { id: '19-161', name: '65. SP District Badin' },
      { id: '19-162', name: '66. DIGP Mirpurkhas Range' },
      { id: '19-163', name: '67. SSP District Mirpurkhas' },
      { id: '19-164', name: '68. SP District Tharparkar' },
      { id: '19-165', name: '69. SP District Umerkot' },
      { id: '19-166', name: '70. DIGP Sukkur Range' },
      { id: '19-167', name: '71. SSP District Sukkur' },
      { id: '19-168', name: '72. SSP District Khairpur' },
      { id: '19-169', name: '73. SP District Ghotki' },
      { id: '19-170', name: '74. DIGP Shaheed Benazirabad Range' },
      { id: '19-171', name: '75. SSP District Shaheed Benazirabad' },
      { id: '19-172', name: '76. SP District Sanghar' },
      { id: '19-173', name: '77. SP District Naushero Feroze' },
      { id: '19-174', name: '78. DIGP Larkana Range' },
      { id: '19-175', name: '79. SSP District Larkana' },
      { id: '19-176', name: '80. SP District Shikarpur' },
      { id: '19-177', name: '81. SSP District Jacobabad' },
      { id: '19-178', name: '82. SP District Kashmore Kandhkot' },
      { id: '19-179', name: '83. SP District Qamber Shahdadkot' },
      { id: '19-2', name: '84. Inspectorate of Prisons, Sindh' },
      { id: '19-3', name: '85. Directorate of Reclamation and Probation, Sindh' },
      { id: '19-4', name: '86. Civil Defence, Sindh' },
      { id: '19-5', name: '87. Forensic Science Laboratory, Sindh' },
      { id: '19-6', name: '88. Counter Terrorism Department (CTD), Sindh' },
      { id: '19-7', name: '89. Special Protection Unit (SPU)' },
      { id: '19-8', name: '90. Sindh Arms License Management System' },
      { id: '19-9', name: '91. Provincial Intelligence Center' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '20',
    srNo: '20.',
    name: 'Industries & Commerce Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '20-1', name: '1. Directorate of Industries, Sindh' },
      { id: '20-2', name: '2. Sindh Small Industries Corporation (SSIC)' },
      { id: '20-3', name: '3. Sindh Industrial Trading Estate (SITE) Limited' },
      { id: '20-4', name: '4. Sindh Investment Board (SBI)' },
      { id: '20-5', name: '5. Printing & Stationery Department, Sindh' },
      { id: '20-6', name: '6. Sugar Factories Control Board' },
      { id: '20-7', name: '7. Consumer Protection Council' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '21',
    srNo: '21.',
    name: 'Information & Archives Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '21-1', name: '1. Directorate of Press Information' },
      { id: '21-2', name: '2. Directorate of Advertisement' },
      { id: '21-3', name: '3. Directorate of Films and Electronic Media' },
      { id: '21-4', name: '4. Sindh Information Commission' },
      { id: '21-5', name: '5. Regional Information Offices (All Divisions)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '22',
    srNo: '22.',
    name: 'Information Science & Technology Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '22-1', name: '1. Sindh IT Board (SITB)' },
      { id: '22-2', name: '2. Directorate of Information Technology' },
      { id: '22-3', name: '3. Arifa Information Technology Park Management' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '23',
    srNo: '23.',
    name: 'Inter Provincial Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '23-1', name: '1. Inter-Provincial Coordination Wing, Karachi' },
      { id: '23-2', name: '2. Council of Common Interests (CCI) Secretariat Support' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '24',
    srNo: '24.',
    name: 'Irrigation Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '24-1', name: '1. Sindh Irrigation & Drainage Authority (SIDA)' },
      { id: '24-2', name: '2. Area Water Boards (Nara, Ghotki, Left Bank, Fuleli)' },
      { id: '24-3', name: '3. Strategic Planning & Reform Unit (SPRU)' },
      { id: '24-4', name: '4. Directorate General, Monitoring & Evaluation, Irrigation' },
      { id: '24-5', name: '5. Office of the Chief Engineer (Irrigation) - All Divisions' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '25',
    srNo: '25.',
    name: 'Governor of Sindh, Governor’s House.',
    focalPerson: 'Principal Secretary',
    offices: [
      { id: '25-1', name: "1. Governor's Secretariat" },
      { id: '25-2', name: '2. Military Secretary to Governor' },
      { id: '25-3', name: '3. Hope Foundation Liaison' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '26',
    srNo: '26.',
    name: 'Katchi Abadies Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '26-444', name: '1. Director General, Sindh Katchi Abadies Authority (SKAA)' },
      { id: '26-445', name: '2. Director Katchi Abadies, Karachi Region' },
      { id: '26-446', name: '3. Director Katchi Abadies, Hyderabad Region' },
      { id: '26-447', name: '4. Director Katchi Abadies, Sukkur Region' },
      { id: '26-448', name: '5. Director Katchi Abadies, Mirpurkhas Region' },
      { id: '26-449', name: '6. Director Katchi Abadies, Shaheed Benazirabad Region' },
      { id: '26-450', name: '7. Director Katchi Abadies, Larkana Region' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '27',
    srNo: '27.',
    name: 'Labour & Human Resources Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '27-1', name: "1. Sindh Employees' Social Security Institution (SESSI)" },
      { id: '27-2', name: '2. Workers Welfare Board, Sindh' },
      { id: '27-3', name: '3. Directorate of Labour, Sindh' },
      { id: '27-4', name: '4. Minimum Wage Board, Sindh' },
      { id: '27-5', name: '5. Office of the Commissioner, Mines Labour Welfare, Sindh' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '28',
    srNo: '28.',
    name: 'Law Parliamentary Affairs, Human Rights Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '28-1', name: '1. Superintendent, District & Session Judge, Karachi South Karachi' },
      { id: '28-2', name: '2. Superintendent, District & Session Judge, Karachi West Karachi' },
      { id: '28-3', name: '3. Superintendent, District & Session Judge, Karachi East Karachi' },
      { id: '28-4', name: '4. Superintendent, District & Session Judge, Karachi Central Karachi' },
      { id: '28-5', name: '5. Superintendent, District & Session Judge, Karachi Malir Karachi' },
      { id: '28-6', name: '6. Superintendent, District & Session Judge, District Hyderabad' },
      { id: '28-7', name: '7. Superintendent, District & Session Judge, District Badin' },
      { id: '28-8', name: '8. Superintendent, District & Session Judge, District Dadu' },
      { id: '28-9', name: '9. Superintendent, District & Session Judge, District Ghotki' },
      { id: '28-10', name: '10. Superintendent, District & Session Judge, District Jacobabad' },
      { id: '28-11', name: '11. Superintendent, District & Session Judge, District Jamshoro' },
      { id: '28-12', name: '12. Superintendent, District & Session Judge, District Qambar Shahdadkot' },
      { id: '28-13', name: '13. Superintendent, District & Session Judge, District Kashmore & Kandhkot' },
      { id: '28-14', name: '14. Superintendent, District & Session Judge, District Khairpur' },
      { id: '28-15', name: '15. Superintendent, District & Session Judge, District Larkana' },
      { id: '28-16', name: '16. Superintendent, District & Session Judge, District Matiari' },
      { id: '28-17', name: '17. Superintendent, District & Session Judge, District Mirpurkhas' },
      { id: '28-18', name: '18. Superintendent, District & Session Judge, District Nausheroferoz' },
      { id: '28-19', name: '19. Superintendent, District & Session Judge, District Nawabshah' },
      { id: '28-20', name: '20. Superintendent, District & Session Judge, District Sanghar' },
      { id: '28-21', name: '21. Superintendent, District & Session Judge, District Shikarpur' },
      { id: '28-22', name: '22. Superintendent, District & Session Judge, District Sukkur' },
      { id: '28-23', name: '23. Superintendent, District & Session Judge, District Tando Allahyar' },
      { id: '28-24', name: '24. Superintendent, District & Session Judge, District Sujawal' },
      { id: '28-25', name: '25. Superintendent, District & Session Judge, District Thatta' },
      { id: '28-26', name: '26. Superintendent, District & Session Judge, District Umerkot' },
      { id: '28-27', name: '27. Superintendent, District & Session Judge, District Tando Muhammad Khan' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '29',
    srNo: '29.',
    name: 'Live Stock & Fisheries Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '29-1', name: '1. Directorate General Livestock, Sindh' },
      { id: '29-2', name: '2. Directorate General Fisheries, Sindh' },
      { id: '29-3', name: '3. Livestock Breeding Services Authority' },
      { id: '29-4', name: '4. Sindh Poultry Vaccine Centre' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '30',
    srNo: '30.',
    name: 'Local Government Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '30-1', name: '1. Sindh Local Government Board' },
      { id: '30-4', name: '2. Malir Development Authority (MDA)' },
      { id: '30-5', name: '3. Lyari Development Authority (LDA)' },
      { id: '30-6', name: '4. Hyderabad Development Authority (HDA)' },
      { id: '30-7', name: '5. Sehwan Development Authority (SDA)' },
      { id: '30-8', name: '6. Larkana Development Authority' },
      { id: '30-9', name: '7. Regional Directorates of Local Government (Divisional)' },
      { id: '30-264', name: '8. Regional Directorate SBCA, Karachi South' },
      { id: '30-265', name: '9. Regional Directorate SBCA, Karachi East' },
      { id: '30-266', name: '10. Regional Directorate SBCA, Karachi West' },
      { id: '30-267', name: '11. Regional Directorate SBCA, Karachi Central' },
      { id: '30-268', name: '12. Regional Directorate SBCA, Sukkur/Hyderabad' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '31',
    srNo: '31.',
    name: 'Master Plan Authority',
    focalPerson: 'Director General',
    offices: [
      { id: '31-1', name: '1. Master Plan Department, Karachi' },
      { id: '31-2', name: '2. Regional Master Plan Units (Hyderabad, Sukkur)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '32',
    srNo: '32.',
    name: 'Mines & Minerals Development, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '32-1', name: '1. Directorate General Mines & Minerals' },
      { id: '32-2', name: '2. Mineral Testing Laboratory' },
      { id: '32-3', name: '3. Licensing & Regulatory Authority for Mining' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '33',
    srNo: '33.',
    name: 'Minorities Affairs Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '33-1', name: '1. Directorate of Minorities Affairs, Sindh' },
      { id: '33-2', name: '2. Sindh Minorities Advisory Council' },
      { id: '33-3', name: '3. Regional Offices, Minorities Affairs' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '34',
    srNo: '34.',
    name: 'Planning & Development, Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '34-1', name: '1. Bureau of Statistics, Sindh' },
      { id: '34-2', name: '2. Sindh Resilience Project' },
      { id: '34-3', name: '3. Public Private Partnership (PPP) Unit, Sindh' },
      { id: '34-4', name: '4. Monitoring & Evaluation Cell (M&E), P&D' },
      { id: '34-5', name: '5. Sindh Strategic Development Institute (SSDI)' },
      { id: '34-6', name: '6. Planning & Development Support Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '35',
    srNo: '35.',
    name: 'Population Welfare, Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '35-1', name: '1. Directorate of Population Welfare, Sindh' },
      { id: '35-2', name: '2. Regional Training Institutes (RTI), Population Welfare' },
      { id: '35-3', name: '3. Family Health Clinics (Across Sindh)' },
      { id: '35-4', name: '4. District Population Welfare Offices' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '36',
    srNo: '36.',
    name: 'Provincial Assembly, Sindh Assembly',
    focalPerson: 'Secretary',
    offices: [
      { id: '36-1', name: '1. Provincial Assembly Secretariat' },
      { id: '36-2', name: '2. Office of the Speaker & Deputy Speaker' },
      { id: '36-3', name: '3. Assembly Committees Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '37',
    srNo: '37.',
    name: 'Peoples Poverty Reduction Programme',
    focalPerson: 'Managing Director',
    offices: [
      { id: '37-1', name: '1. PPRP Regional Management Unit' },
      { id: '37-2', name: '2. District Implementation Units' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '38',
    srNo: '38.',
    name: 'Services, General Administration & Coordination Department, Government of Sindh',
    focalPerson: 'Secretary (Services)',
    offices: [
      { id: '38-1', name: '1. Commissioner, Karachi Division' },
      { id: '38-2', name: '2. Deputy Commissioner Karachi, District South' },
      { id: '38-3', name: '3. Deputy Commissioner Karachi, District East' },
      { id: '38-4', name: '4. Deputy Commissioner Karachi, District West' },
      { id: '38-5', name: '5. Deputy Commissioner Karachi, District Central' },
      { id: '38-6', name: '6. Deputy Commissioner Karachi, District Malir' },
      { id: '38-7', name: '7. Deputy Commissioner Karachi, District Korangi' },
      { id: '38-8', name: '8. Deputy Commissioner Karachi, District Keamari' },
      { id: '38-9', name: '9. Commissioner Hyderabad Division' },
      { id: '38-10', name: '10. Deputy Commissioner, District Hyderabad' },
      { id: '38-11', name: '11. Deputy Commissioner, District Tando Allahyar' },
      { id: '38-12', name: '12. Deputy Commissioner, District Dadu' },
      { id: '38-13', name: '13. Deputy Commissioner, District Tando Muhammad Khan' },
      { id: '38-14', name: '14. Deputy Commissioner, District Matiari' },
      { id: '38-15', name: '15. Deputy Commissioner, District Jamshoro' },
      { id: '38-16', name: '16. Deputy Commissioner, District Thatta' },
      { id: '38-17', name: '17. Deputy Commissioner, District Sujawal' },
      { id: '38-18', name: '18. Deputy Commissioner, District Badin' },
      { id: '38-19', name: '19. Commissioner Sukkur Division' },
      { id: '38-20', name: '20. Deputy Commissioner, District Sukkur' },
      { id: '38-21', name: '21. Deputy Commissioner, District Khairpur' },
      { id: '38-22', name: '22. Deputy Commissioner, District Ghotki' },
      { id: '38-23', name: '23. Commissioner Shaheed Benazirabad Division' },
      { id: '38-24', name: '24. Deputy Commissioner District Shaheed Benazirabad' },
      { id: '38-25', name: '25. Deputy Commissioner, District Saanghar' },
      { id: '38-26', name: '26. Deputy Commissioner, District Naushehro Feroz' },
      { id: '38-27', name: '27. Commissioner Mirpurkhas Division' },
      { id: '38-28', name: '28. Deputy Commissioner, District Mirpurkhas' },
      { id: '38-29', name: '29. Deputy Commissioner, District Tharparkar' },
      { id: '38-30', name: '30. Deputy Commissioner, District Umerkot' },
      { id: '38-31', name: '31. Commissioner Larkana Division' },
      { id: '38-32', name: '32. Deputy Commissioner District Larkana' },
      { id: '38-33', name: '33. Deputy Commissioner District Shikarpur' },
      { id: '38-34', name: '34. Deputy Commissioner, District Jacobabad' },
      { id: '38-35', name: '35. Deputy Commissioner District Kashmore Kandhkot' },
      { id: '38-36', name: '36. Deputy Commissioner, District Qambar Shahdadkot' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '39',
    srNo: '39.',
    name: 'Sindh Commission on The Status of Women, Government of Sindh',
    focalPerson: 'Chairperson',
    offices: [
      { id: '39-1', name: '1. Secretariat of the Commission' },
      { id: '39-2', name: '2. Research & Advocacy Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '40',
    srNo: '40.',
    name: 'Sindh Mental Health, Government of Sindh',
    focalPerson: 'Chairman',
    offices: [
      { id: '40-1', name: '1. Sindh Mental Health Authority (SMHA)' },
      { id: '40-2', name: '2. Sir Cowasjee Jehangir Institute of Psychiatry and Behavioral Sciences, Hyderabad' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '41',
    srNo: '41.',
    name: 'Sindh Higher Education Commission',
    focalPerson: 'Chairman',
    offices: [
      { id: '41-1', name: '1. Sindh HEC Secretariat' },
      { id: '41-2', name: '2. Research & Curriculum Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '42',
    srNo: '42.',
    name: 'Social Welfare Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '42-1', name: '1. Director Social Welfare Department, Sukkur Division Sukkur' },
      { id: '42-2', name: '2. Additional Director, Social Welfare, District Sukkur' },
      { id: '42-3', name: '3. Additional Director, Social Welfare, District Khairpur' },
      { id: '42-4', name: '4. Additional Director, Social Welfare, District Ghotki' },
      { id: '42-5', name: '5. Director Social Welfare Department, Larkana Division, Larkana' },
      { id: '42-6', name: '6. Additional Director, Social Welfare, District Larkana' },
      { id: '42-7', name: '7. Additional Director, Social Welfare, District Shikarpur' },
      { id: '42-8', name: '8. Additional Director, Social Welfare, District Jacobabad' },
      { id: '42-9', name: '9. Additional Director, Social Welfare, District Kashmore Kandhkot' },
      { id: '42-10', name: '10. Additional Director, Social Welfare, District Qambar Shahdadkot' },
      { id: '42-11', name: '11. Director Social Welfare Department, Mirpurkhas Division, Mirpurkhas' },
      { id: '42-12', name: '12. Additional Director, Social Welfare, District Mirpurkhas' },
      { id: '42-13', name: '13. Additional Director, Social Welfare, District Tharparkar' },
      { id: '42-14', name: '14. Additional Director, Social Welfare, District Umerkot' },
      { id: '42-15', name: '15. Director Social Welfare Department, Hyderabad Division, Hyderabad' },
      { id: '42-16', name: '16. Additional Director, Social Welfare, District Hyderabad' },
      { id: '42-17', name: '17. Additional Director, Social Welfare, District Tando Allahyar' },
      { id: '42-18', name: '18. Additional Director, Social Welfare, District Dadu' },
      { id: '42-19', name: '19. Additional Director, Social Welfare, District Tando Muhammad Khan' },
      { id: '42-20', name: '20. Additional Director, Social Welfare, District Matiari' },
      { id: '42-21', name: '21. Additional Director, Social Welfare, District Jamshoro' },
      { id: '42-22', name: '22. Additional Director, Social Welfare, District Thatta' },
      { id: '42-23', name: '23. Additional Director, Social Welfare, District Sujawal' },
      { id: '42-24', name: '24. Additional Director, Social Welfare, District Badin' },
      { id: '42-25', name: '25. Director Social Welfare Department, Shaheed Benazirabad Division, SBA' },
      { id: '42-26', name: '26. Additional Director, Social Welfare, District Shaheed Benazirabad' },
      { id: '42-27', name: '27. Additional Director, Social Welfare, District Sanghar' },
      { id: '42-28', name: '28. Additional Director, Social Welfare, District Naushehro Feroze' },
      { id: '42-29', name: '29. Director Social Welfare Department, Karachi' },
      { id: '42-30', name: '30. Director General (SCPA), Social Welfare Department, Karachi' },
      { id: '42-31', name: '31. Director General (Field), Social Welfare Department, Karachi' },
      { id: '42-32', name: '32. Director General (Charity Commission), Social Welfare, Karachi' },
      { id: '42-33', name: '33. Additional Director, Social Welfare, District South, Karachi' },
      { id: '42-34', name: '34. Additional Director, Social Welfare, District East, Karachi' },
      { id: '42-35', name: '35. Additional Director, Social Welfare, District West, Karachi' },
      { id: '42-36', name: '36. Additional Director, Social Welfare, District Central, Karachi' },
      { id: '42-37', name: '37. Additional Director, Social Welfare, District Malir, Karachi' },
      { id: '42-38', name: '38. Additional Director, Social Welfare, District Korangi, Karachi' },
      { id: '42-39', name: '39. Additional Director, Social Welfare, District Keamari, Karachi' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '43',
    srNo: '43.',
    name: 'Sindh Public Procurement Regulatory Authority, Government of Sindh',
    focalPerson: 'Managing Director',
    offices: [
      { id: '43-1', name: '1. Monitoring & Evaluation Division, SPPRA' },
      { id: '43-2', name: '2. Capacity Building and Training Unit' },
      { id: '43-3', name: '3. IT & MIS Section, SPPRA' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '44',
    srNo: '44.',
    name: 'Sindh Education Endowment Fund, Government of Sindh',
    focalPerson: 'Managing Director',
    offices: [
      { id: '44-1', name: '1. SEEF Trust Management Unit' },
      { id: '44-2', name: '2. Scholarship Coordination Section' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '45',
    srNo: '45.',
    name: 'Sindh Child Protection Authority, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '45-1', name: '1. Sindh Child Protection Authority (SCPA) Head Office' },
      { id: '45-2', name: '2. Child Protection Units (Divisional)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '46',
    srNo: '46.',
    name: 'Sports & Youth Affairs Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '46-1', name: '1. Directorate of Sports, Sindh' },
      { id: '46-2', name: '2. Sindh Sports Board' },
      { id: '46-3', name: '3. Youth Affairs Wing' },
      { id: '46-4', name: '4. Divisional Sports Offices (All Divisions)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '47',
    srNo: '47.',
    name: 'The Inspector General Prisons Central Prison, Government of Sindh',
    focalPerson: 'Inspector General',
    offices: [
      { id: '47-1', name: '1. Inspectorate General of Prisons, Sindh' },
      { id: '47-2', name: '2. Central Prison Karachi' },
      { id: '47-3', name: '3. Central Prison Hyderabad' },
      { id: '47-4', name: '4. Central Prison Sukkur' },
      { id: '47-5', name: '5. District Jails Management Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '48',
    srNo: '48.',
    name: 'The Director General, Sindh Environmental Protection Agency, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '48-1', name: '1. SEPA Regional Office, Karachi' },
      { id: '48-2', name: '2. SEPA Regional Office, Hyderabad' },
      { id: '48-3', name: '3. SEPA Regional Office, Sukkur' },
      { id: '48-4', name: '4. SEPA Regional Office, Larkana' },
      { id: '48-5', name: '5. Industrial Pollution Control Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '49',
    srNo: '49.',
    name: 'Thar Coal & Energy Board, Government of Sindh',
    focalPerson: 'Managing Director',
    offices: [
      { id: '49-1', name: '1. Thar Coal & Energy Board Secretariat' },
      { id: '49-2', name: '2. Technical Evaluation Committee, TCEB' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '50',
    srNo: '50.',
    name: 'Transport & Mass Transit Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '50-1', name: '1. Sindh Mass Transit Authority (SMTA)' },
      { id: '50-2', name: '2. Provincial Transport Authority (PTA)' },
      { id: '50-3', name: '3. Regional Transport Authority (RTA) - All Divisions' },
      { id: '50-4', name: '4. Sindh Road Transport Corporation (SRTC) - Assets Management' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '51',
    srNo: '51.',
    name: 'The Director General, Zulifqarabad Development Authority, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '51-1', name: '1. ZDA Secretariat, Karachi' },
      { id: '51-2', name: '2. Infrastructure Development Wing, ZDA' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '52',
    srNo: '52.',
    name: 'Training Management & Research Tmr Wing, SGA&Cd',
    focalPerson: 'Director General',
    offices: [
      { id: '52-1', name: '1. TMR Wing Secretariat (SGA&CD)' },
      { id: '52-2', name: '2. Management and Training Unit' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '53',
    srNo: '53.',
    name: 'The Directorate General, Provincial Disaster Management Authority, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '53-1', name: '1. PDMA Operations Centre, Karachi' },
      { id: '53-2', name: '2. Regional Disaster Management Offices (All Divisions)' },
      { id: '53-3', name: '3. Relief and Logistics Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '54',
    srNo: '54.',
    name: 'The Prosecutor General Sindh, Government of Sindh',
    focalPerson: 'Prosecutor General',
    offices: [
      { id: '54-1', name: '1. Office of the Prosecutor General, Sindh' },
      { id: '54-2', name: '2. District Public Prosecutors (All Districts)' },
      { id: '54-3', name: '3. Special Prosecutors for Anti-Terrorism Courts' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '55',
    srNo: '55.',
    name: 'The Official Assignee',
    focalPerson: 'Official Assignee',
    offices: [
      { id: '55-1', name: '1. Office of the Official Assignee, High Court of Sindh, Karachi' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '56',
    srNo: '56.',
    name: 'The Directorate General Sindh Coastal Development Authority, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '56-1', name: '1. SCDA Head Office, Karachi' },
      { id: '56-2', name: '2. Coastal Community Development Project Units' },
      { id: '56-3', name: '3. Marine Research & Development Wing' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '57',
    srNo: '57.',
    name: 'Universities & Boards Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '57-1', name: '1. Shaheed Benazir Bhutto University Lyari Karachi' },
      { id: '57-2', name: '2. Dow University of Health Sciences, Karachi' },
      { id: '57-3', name: '3. Institute of Business Administration, University, Karachi' },
      { id: '57-4', name: '4. Jinnah Sindh Medical University, Karachi' },
      { id: '57-5', name: '5. NED University, of Engineering & Technology, Karachi' },
      { id: '57-6', name: '6. Sindh Madaresatul Islam University, Karachi' },
      { id: '57-7', name: '7. Shaheed Zulfiqar Ali Bhutto University of Law, Karachi' },
      { id: '57-8', name: '8. University of Karachi' },
      { id: '57-9', name: '9. Dawood University of Engineering & Technology, Karachi.' },
      { id: '57-10', name: '10. Shah Abdul Latif University, Khairpur' },
      { id: '57-11', name: '11. Benazir Bhutto Shaheed University of Technology & Skill Development Khairpur Mirs.' },
      { id: '57-12', name: '12. Institute of Business Administration, University, Sukkur' },
      { id: '57-13', name: '13. Begum Nusrat Bhutto Women University, Sukkur' },
      { id: '57-14', name: '14. Aror University of ARt, Architecture, Design & Heritages, Sukkur' },
      { id: '57-15', name: '15. Peoples University of Medical & Health Sciences for Women, Nawabshah' },
      { id: '57-16', name: '16. Quaid-e-Awam University of Engineering Sciences, & Technology, Nawabshah' },
      { id: '57-17', name: '17. Shaheed Benazir Bhutto University, Shaheed Benazirabad' },
      { id: '57-18', name: '18. Shaheed Benazir Bhutto University of Veterinary & Animal Sciences, Sakrand.' },
      { id: '57-19', name: '19. Liaquat University of Medical & Health Sciences, District Jamshoro' },
      { id: '57-20', name: '20. Mehran University of Engineering & TEchnology, Jamshoro' },
      { id: '57-21', name: '21. Shaheed Allah Buksh University of ARt, Design & Heritages, Jamshoro' },
      { id: '57-22', name: '22. University of Sindh, Jamshoro' },
      { id: '57-23', name: '23. Government College University, Hyderabad' },
      { id: '57-24', name: '24. Sindh Agriculture University Tando Jam' },
      { id: '57-25', name: '25. The University of Sufism & Modern Sciences, Bhitshah' },
      { id: '57-26', name: '26. Board of Intermediate Education, Karachi' },
      { id: '57-27', name: '27. Board Secondary education, Karachi' },
      { id: '57-28', name: '28. Board of Intermediate & Secondary Education, Hyderabad' },
      { id: '57-29', name: '29. Board of Intermediate & Secondary Education, Sukkur' },
      { id: '57-30', name: '30. Board of Intermediate & Secondary Education, Larkana' },
      { id: '57-31', name: '31. Board of Intermediate & Secondary Education, Mirpurkhas' },
      { id: '57-32', name: '32. Board of Intermediate & Secondary Education, SBA' },
      { id: '57-33', name: '33. Sindh Board of Technical Education, Karachi' },
      { id: '57-34', name: '34. Sindh TEchnical Education & Vocational Training Authority (STEVTA), Karachi' },
      { id: '57-35', name: '35. Benazir Bhutto Shaheed Human Resources Research & Development Board (BBSHRRDB), Karachi' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '58',
    srNo: '58.',
    name: 'Wildlife Department Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '58-1', name: '1. Office of the Chief Conservator Wildlife, Sindh' },
      { id: '58-2', name: '2. Conservator Wildlife, Karachi Region' },
      { id: '58-3', name: '3. Conservator Wildlife, Hyderabad Region' },
      { id: '58-4', name: '4. Conservator Wildlife, Sukkur Region' },
      { id: '58-5', name: '5. Conservator Wildlife, Larkana Region' },
      { id: '58-6', name: '6. Conservator Wildlife, Mirpurkhas Region' },
      { id: '58-7', name: '7. Conservator Wildlife, Shaheed Benazirabad Region' },
      { id: '58-8', name: '8. Kirthar National Park Management Unit' },
      { id: '58-9', name: '9. Sindh Wildlife Research & Training Centre, Karachi' },
      { id: '58-10', name: '10. Wildlife Rescue Centre, Karachi' },
      { id: '58-11', name: '11. Directorate of Haleji Lake (Wildlife Sanctuary)' },
      { id: '58-12', name: '12. Management Unit, Indus Dolphin Reserve, Sukkur' },
      { id: '58-13', name: '13. Wildlife GIS & Monitoring Lab, Karachi' },
      { id: '58-14', name: '14. Mobile Wildlife Squad (Province wide)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '59',
    srNo: '59.',
    name: 'Women Development Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '59-1', name: '1. Directorate of Women Development, Sindh' },
      { id: '59-2', name: '2. Women Complaint Centre, Karachi' },
      { id: '59-3', name: '3. Women Complaint Centre, Hyderabad' },
      { id: '59-4', name: '4. Women Complaint Centre, Sukkur' },
      { id: '59-5', name: '5. Women Complaint Centre, Larkana' },
      { id: '59-6', name: '6. Women Complaint Centre, Mirpurkhas' },
      { id: '59-7', name: '7. Women Complaint Centre, Shaheed Benazirabad' },
      { id: '59-8', name: '8. Working Women Hostel, Karachi' },
      { id: '59-9', name: '9. Working Women Hostel, Hyderabad' },
      { id: '59-10', name: '10. Working Women Hostel, Sukkur' },
      { id: '59-11', name: '11. Working Women Hostel, Larkana' },
      { id: '59-12', name: '12. Working Women Hostel, Shaheed Benazirabad' },
      { id: '59-13', name: '13. Day Care Centre, Sindh Secretariat, Karachi' },
      { id: '59-14', name: '14. Women Improvement Centres (WIC) Network' },
      { id: '59-15', name: '15. Sales & Display Centre for Women Artisans, Karachi' },
      { id: '59-16', name: '16. Legal Aid & Counseling Units for Women' },
      { id: '59-17', name: '17. Crisis Centres for Women (Regional Offices)' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '60',
    srNo: '60.',
    name: 'Works & Services Department, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '60-1', name: '1. Chief Engineer (Buildings), Karachi' },
      { id: '60-2', name: '2. Chief Engineer (Buildings), Hyderabad' },
      { id: '60-3', name: '3. Chief Engineer (Buildings), Sukkur' },
      { id: '60-4', name: '4. Chief Engineer (Buildings), Larkana' },
      { id: '60-5', name: '5. Chief Engineer (Highways), Hyderabad' },
      { id: '60-6', name: '6. Chief Engineer (Highways), Sukkur' },
      { id: '60-7', name: '7. Chief Engineer (Highways), Larkana' },
      { id: '60-8', name: '8. Chief Engineer (Electrical), Karachi' },
      { id: '60-9', name: '9. Chief Engineer (Electrical), Hyderabad' },
      { id: '60-10', name: '10. Research & Training Institute (RTI), Works & Services Department' },
      { id: '60-11', name: '11. Directorate of Design, Works & Services Department' },
      { id: '60-12', name: '12. Monitoring & Evaluation Cell, Works & Services Department' },
      { id: '60-13', name: '13. Foreign Aided Projects (FAP) Directorate, Works & Services Department' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '61',
    srNo: '61.',
    name: 'PPHI Sindh (Regional & District Management), Government of Sindh',
    focalPerson: 'CEO',
    offices: [
      { id: '61-1', name: '1. Regional Director, PPHI Sindh, Karachi Region' },
      { id: '61-338', name: '2. District Manager, PPHI Sindh, District South, Karachi' },
      { id: '61-339', name: '3. District Manager, PPHI Sindh, District East, Karachi' },
      { id: '61-340', name: '4. District Manager, PPHI Sindh, District West, Karachi' },
      { id: '61-341', name: '5. District Manager (Primary), PPHI Sindh, District Malir, Karachi' },
      { id: '61-342', name: '6. District Manager (Secondary), PPHI Sindh, District Malir, Karachi' },
      { id: '61-343', name: '7. District Manager, PPHI Sindh, District Keamari, Karachi' },
      { id: '61-345', name: '8. District Manager, PPHI Sindh, District Central, Karachi' },
      { id: '61-346', name: '9. Chief Executive Officer, PPHI Sindh, Head Office' },
      { id: '61-347', name: '10. Regional Director, PPHI Sindh, Sukkur Region' },
      { id: '61-348', name: '11. District Manager, PPHI Sindh, District Sukkur' },
      { id: '61-349', name: '12. District Manager, PPHI Sindh, District Khairpur' },
      { id: '61-350', name: '13. District Manager, PPHI Sindh, District Ghotki' },
      { id: '61-351', name: '14. Regional Director, PPHI Sindh, Larkana Region' },
      { id: '61-352', name: '15. District Manager (Primary), PPHI Sindh, District Larkana' },
      { id: '61-353', name: '16. District Manager, PPHI Sindh, District Shikarpur' },
      { id: '61-354', name: '17. District Manager (Secondary), PPHI Sindh, District Larkana' },
      { id: '61-355', name: '18. District Manager, PPHI Sindh, District Kashmore Kandhkot' },
      { id: '61-356', name: '19. District Manager, PPHI Sindh, District Qambar Shahdadkot' },
      { id: '61-357', name: '20. District Manager, PPHI Sindh, District Jacobabad' },
      { id: '61-358', name: '21. Regional Director, PPHI Sindh, Hyderabad Region' },
      { id: '61-359', name: '22. District Manager, PPHI Sindh, District Hyderabad' },
      { id: '61-360', name: '23. District Manager, PPHI Sindh, District Tando Allahyar' },
      { id: '61-361', name: '24. District Manager, PPHI Sindh, District Dadu' },
      { id: '61-362', name: '25. District Manager, PPHI Sindh, District Tando Muhammad Khan' },
      { id: '61-363', name: '26. District Manager, PPHI Sindh, District Matiari' },
      { id: '61-364', name: '27. District Manager, PPHI Sindh, District Jamshoro' },
      { id: '61-365', name: '28. District Manager, PPHI Sindh, District Thatta' },
      { id: '61-366', name: '29. District Manager, PPHI Sindh, District Sujawal' },
      { id: '61-367', name: '30. District Manager, PPHI Sindh, District Badin' },
      { id: '61-368', name: '31. Regional Director, PPHI Sindh, Mirpurkhas Region' },
      { id: '61-369', name: '32. District Manager, PPHI Sindh, District Mirpurkhas' },
      { id: '61-370', name: '33. District Manager, PPHI Sindh, District Tharparkar' },
      { id: '61-371', name: '34. District Manager, PPHI Sindh, District Umerkot' },
      { id: '61-372', name: '35. Regional Director, PPHI Sindh, Shaheed Benazirabad Region' },
      { id: '61-373', name: '36. District Manager, PPHI Sindh, District Shaheed Benazirabad' },
      { id: '61-374', name: '37. District Manager, PPHI Sindh, District Sanghar' },
      { id: '61-375', name: '38. District Manager, PPHI Sindh, District Naushero Feroze' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '62',
    srNo: '62.',
    name: 'KW&SC Karachi (Water & Sewerage), Government of Sindh',
    focalPerson: 'Managing Director',
    offices: [
      { id: '62-376', name: '1. Managing Director, Karachi Water & Sewerage Corporation' },
      { id: '62-377', name: '2. Executive Engineer (XEN), KW&SC, Lyari Town, District South' },
      { id: '62-378', name: '3. Executive Engineer (XEN), KW&SC, Saddar Town, District South' },
      { id: '62-379', name: '4. Executive Engineer (XEN), KW&SC, Aram Bagh Town, District South' },
      { id: '62-380', name: '5. Executive Engineer (XEN), KW&SC, Civil Line Town, District South' },
      { id: '62-381', name: '6. Executive Engineer (XEN), KW&SC, Garden Town, District South' },
      { id: '62-382', name: '7. Executive Engineer (XEN), KW&SC, Gulistan-e-Jauhar Town, District East' },
      { id: '62-383', name: '8. Executive Engineer (XEN), KW&SC, Gulshan Town, District East' },
      { id: '62-384', name: '9. Executive Engineer (XEN), KW&SC, Jamshed Town, District East' },
      { id: '62-385', name: '10. Executive Engineer (XEN), KW&SC, Ferozabad Town, District East' },
      { id: '62-386', name: '11. Executive Engineer (XEN), KW&SC, Gulshan-e-Iqbal Town, District East' },
      { id: '62-387', name: '12. Executive Engineer (XEN), KW&SC, Gulzar-e-Hijri Town, District East' },
      { id: '62-388', name: '13. Executive Engineer (XEN), KW&SC, Orangi Town, District West' },
      { id: '62-389', name: '14. Executive Engineer (XEN), KW&SC, Manghopir Town, District West' },
      { id: '62-390', name: '15. Executive Engineer (XEN), KW&SC, Maripur Town, District West' },
      { id: '62-391', name: '16. Executive Engineer (XEN), KW&SC, Mominabad Town, District West' },
      { id: '62-392', name: '17. Executive Engineer (XEN), KW&SC, Ittehad Town, District West' },
      { id: '62-393', name: '18. Executive Engineer (XEN), KW&SC, Baldia Town, District West' },
      { id: '62-394', name: '19. Executive Engineer (XEN), KW&SC, Gulberg Town, District Central' },
      { id: '62-395', name: '20. Executive Engineer (XEN), KW&SC, Liaquatabad Town, District Central' },
      { id: '62-396', name: '21. Executive Engineer (XEN), KW&SC, New Karachi Town, District Central' },
      { id: '62-397', name: '22. Executive Engineer (XEN), KW&SC, North Nazimabad Town, District Central' },
      { id: '62-398', name: '23. Executive Engineer (XEN), KW&SC, Nazimabad Town, District Central' },
      { id: '62-399', name: '24. Executive Engineer (XEN), KW&SC, Keamari Town, District Keamari' },
      { id: '62-400', name: '25. Executive Engineer (XEN), KW&SC, Baldia Town, District Keamari' },
      { id: '62-401', name: '26. Executive Engineer (XEN), KW&SC, S.I.T.E. Town, District Keamari' },
      { id: '62-402', name: '27. Executive Engineer (XEN), KW&SC, Karachi Fish Harbour Town, District Keamari' },
      { id: '62-403', name: '28. Executive Engineer (XEN), KW&SC, Korangi Town, District Korangi' },
      { id: '62-404', name: '29. Executive Engineer (XEN), KW&SC, Landhi Town, District Korangi' },
      { id: '62-405', name: '30. Executive Engineer (XEN), KW&SC, Shah Faisal Town, District Korangi' },
      { id: '62-406', name: '31. Executive Engineer (XEN), KW&SC, Model Colony Town, District Korangi' },
      { id: '62-407', name: '32. Executive Engineer (XEN), KW&SC, Malir Town, District Malir' },
      { id: '62-408', name: '33. Executive Engineer (XEN), KW&SC, Bin Qasim Town, District Malir' },
      { id: '62-409', name: '34. Executive Engineer (XEN), KW&SC, Gadap Town, District Malir' },
      { id: '62-410', name: '35. Executive Engineer (XEN), KW&SC, Jinnah Town, District Malir' },
      { id: '62-411', name: '36. Executive Engineer (XEN), KW&SC, Ibrahim Hyderi Town, District Malir' },
      { id: '62-412', name: '37. Executive Engineer (XEN), KW&SC, Murad Memon Town, District Malir' },
      { id: '62-413', name: '38. Executive Engineer (XEN), KW&SC, Shah Murad Town, District Malir' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '63',
    srNo: '63.',
    name: 'Forest Department & Specialized Projects, Government of Sindh',
    focalPerson: 'Secretary',
    offices: [
      { id: '63-472', name: '1. Project Director, Competitive and Livable City of Karachi (CLICK)' },
      { id: '63-473', name: '2. Chief Conservator of Forests, Sindh, (Social Forestry) Hyderabad' },
      { id: '63-474', name: '3. Conservator of Forest, (Social Forestry) Karachi-I' },
      { id: '63-475', name: '4. Divisional Forest Officer, (Social Forestry) Karachi-I' },
      { id: '63-476', name: '5. Divisional Forest Officer, (Social Forestry) Karachi-II' },
      { id: '63-477', name: '6. Divisional Forest Officer, (Social Forestry) Thatta' },
      { id: '63-478', name: '7. Conservator of Forest, (Social Forestry) Hyderabad' },
      { id: '63-479', name: '8. Divisional Forest Officer, (Social Forestry) Hyderabad' },
      { id: '63-480', name: '9. Divisional Forest Officer, (Social Forestry) Mirpurkhas' },
      { id: '63-481', name: '10. Divisional Forest Officer, (Social Forestry) Tando Allahyar' },
      { id: '63-482', name: '11. Divisional Forest Officer, (Social Forestry) Sanghar' },
      { id: '63-483', name: '12. Divisional Forest Officer, (Social Forestry) Tando Muhammad Khan' },
      { id: '63-484', name: '13. Conservator of Forest, (Social Forestry) Sukkur' },
      { id: '63-485', name: '14. Divisional Forest Officer, (Social Forestry) Sukkur' },
      { id: '63-486', name: '15. Divisional Forest Officer, (Social Forestry) Ghotki' },
      { id: '63-487', name: '16. Divisional Forest Officer, (Social Forestry) Khairpur' },
      { id: '63-488', name: '17. Divisional Forest Officer, (Social Forestry) Shikarpur' },
      { id: '63-489', name: '18. Divisional Forest Officer, (Social Forestry) Jacobabad' },
      { id: '63-490', name: '19. Conservator of Forest, (Social Forestry) Larkana' },
      { id: '63-491', name: '20. Divisional Forest Officer, (Social Forestry) Larkana' },
      { id: '63-492', name: '21. Divisional Forest Officer, (Social Forestry) Qambar Shahdadkot' },
      { id: '63-493', name: '22. Divisional Forest Officer, (Social Forestry) Benazirabad' },
      { id: '63-494', name: '23. Divisional Forest Officer, (Social Forestry) Dadu' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '64',
    srNo: '64.',
    name: 'Sindh Food Authority, Government of Sindh',
    focalPerson: 'Director General',
    offices: [
      { id: '64-495', name: '1. Director General, Sindh Food Authority' },
      { id: '64-496', name: '2. Deputy Director District South, Sindh Food Authority' },
      { id: '64-497', name: '3. Deputy Director District East, Sindh Food Authority' },
      { id: '64-498', name: '4. Deputy Director District West, Sindh Food Authority' },
      { id: '64-499', name: '5. Deputy Director District Central, Sindh Food Authority' },
      { id: '64-500', name: '6. Deputy Director District Malir, Sindh Food Authority' },
      { id: '64-501', name: '7. Deputy Director District Korangi, Sindh Food Authority' },
      { id: '64-502', name: '8. Deputy Director District Keamari, Sindh Food Authority' },
    ],
    officialName: '',
    jobDescription: '',
  },
  {
    id: '65',
    srNo: '65.',
    name: 'Other Departments/Bodies, Government of Sindh',
    focalPerson: 'Chairman',
    offices: [
      { id: '65-610', name: '1. Chairman, Shaheed Benazir Bhutto Housing Cell' },
      { id: '65-611', name: '2. Director, Denning Law School Karachi' },
    ],
    officialName: '',
    jobDescription: '',
  },
];

